### ISSUE TITLE
No support for django 5.1

### ISSUE THREAD

**Issue by Buczek05** [mfogel/django-timezone-field#141]
<img width="467" alt="Screenshot 2024-08-15 at 10 18 10" src="https://github.com/user-attachments/assets/a96516c5-7edb-472e-89c0-6f74f230688c">

**Comment by mfogel** [comment]
Looks like this was caused by django-celery-beat 2.6.0 not supporting django 5.1. The upgrade of django forced the downgrade of django-celery-beat to 2.1.0, which had a dependency on django-timezone-field < 5.0, hence the downgrade of django-timezone-field.

django-celery-beat 2.7.0 was released on Aug 22, fixing this whole mess, so `poetry update` should now work for you... please re-open if it doesn't. Cheers.

More info in https://github.com/celery/django-celery-beat/issues/781.
