### ISSUE TITLE
Show timezone offset of timezoness in dropdown

### ISSUE THREAD

**Issue by martinvol** [mfogel/django-timezone-field#41]
I am looking to get a form like the one Slack has 

![image](https://user-images.githubusercontent.com/698027/27245439-ee566ed6-52c1-11e7-9858-e592ca625374.png)

is this posible using `django-timezone-field`?

**Comment by mfogel** [comment]
Hi @martinvol I imagine you long ago found a solution to this, but for others that may be interseted:

The approach I would take to do this is, in my form class, use the [form field from django-timezone-field](https://github.com/mfogel/django-timezone-field/blob/2.0/timezone_field/forms.py#L6), with a custom [choices argument](https://docs.djangoproject.com/en/1.11/ref/forms/fields/#django.forms.ChoiceField.choices). If that turned out to unable to produce the format I wanted, I would look into subclassing the form field with a custom form field of my own.
